name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t krishna/docker-reactapp -f Dockerfile.dev .
      - run: docker run -e CI=true krishna/docker-reactapp npm run test
